// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"entgo.io/bug/ent/post"
	"entgo.io/bug/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postMixin := schema.Post{}.Mixin()
	postMixinHooks0 := postMixin[0].Hooks()
	post.Hooks[0] = postMixinHooks0[0]
}

const (
	Version = "v0.10.2-0.20220429094929-9d992c4f41ec"           // Version of ent codegen.
	Sum     = "h1:hlQXx+gj9ID9MEcYCA2YKNQ7TKjneI5bR2wlhHTyAzA=" // Sum of ent codegen.
)
